# Generated by Django 4.2.10 on 2024-08-18 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_balance', to=settings.AUTH_USER_MODEL, verbose_name='Баланс'),
            preserve_default=False,
        ),
    ]
