# Generated by Django 4.2.10 on 2024-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_balance_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.IntegerField(default=1000, verbose_name='Значение баланса'),
        ),
    ]
