# Generated by Django 4.2.10 on 2024-08-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='value',
            field=models.PositiveIntegerField(default=1000, verbose_name='Значение баланса'),
        ),
    ]
