# Generated by Django 4.2.10 on 2024-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_title_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
    ]
