# Generated by Django 4.2.10 on 2024-08-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='title_lessons',
        ),
    ]
