# Generated by Django 4.2.10 on 2024-08-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_name_course_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title_lessons',
            new_name='title',
        ),
    ]
