# Generated by Django 4.2.10 on 2024-08-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_title_lessons_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
